NiklasMerz/cordova-plugin-fingerprint-aio

- plugin.xml
- res/android/values-zh/fpauth-strings.xml
Add chinese language for Android
> Add chinese language for Android

- src/ios/Fingerprint.swift
> Add reason ios

- plugin.xml
Set plugin version in plugin.xml
NPM version set on release
> Plugin XML version

- README.md
- package.json
> Add notes and dependancy for XCode 9 beta 

- .eslintrc.json
- README.md
- package.json
- www/Fingerprint.js
> Add eslint

- src/android/FingerprintAuthenticationDialogFragment.java
Go to backup only if FragmentActivity is open.
> Check Activity open before going to backup

- res/android/values-it/fpauth-strings.xml
Updated values folder for italian translation.
> Added italian translations.

- plugin.xml
I have updated the plugin.xml.
> Added the reference for Italian and Greek translations.

- src/ios/Fingerprint.swift
> Fix iOS 9 and above support

- src/android/Fingerprint.java
> Create new key when current key is invalid

- .vscode/settings.json
- README.md
- plugin.xml
- src/android/Fingerprint.java
- src/ios/Fingerprint.swift
- tests/tests.js
> Add check if faceid or touchid is available

- res/android/values-it/fpauth-strings.xml
Fixed a misspelled italian word, let me know if this is ok
> Fixed italian typo

- src/ios/Fingerprint.swift
> Return biometic type none for ios fallback

- plugin.xml
@NiklasMerz Looks like maybe a copy/paste or conflict fixing error?
> remove extraneous "+"s

- plugin.xml
> Support Cordova-android 7.0 and fix fingerprint permission in 6.x

- src/android/Fingerprint.java
close #96 fixes #77
Signed-off-by: Niklas Merz <NiklasMerz@gmx.net>
> Fixed issue Illegal state exception

- plugin.xml
- res/android/values-nl/fpauth-strings.xml
Added values-nl folder under resources and updated its reference in plugin.xml
> Dutch Translation added

- src/android/Fingerprint.java
FIX #77 
Added changes from original Android repo (mjwheatley/cordova-plugin-android-fingerprint-auth#54)
> Hotfix android illegal state

- README.md
* some minor changes to spelling/grammar
* highlight allowed boolean values for backup parameter as code block
* embedded links to licenses
No test needed because only README was updated
> some README update proposals

- package.json
May be necessary for Xcode 10.1
> Use build flag for new Xcode

- plugin.xml
- src/ios/Bridging-Header.h
Adds Objective-C headers
Fixes #140
> Add Objective-C headers

- plugin.xml
- res/android/values-ru/fpauth-strings.xml
> add russian translation

- src/android/Fingerprint.java
- src/ios/Fingerprint.swift
- tests/tests.js
Changes the return of isAvailable from a string to a json object to display different types of errors
https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/166
Closes #166
> Make isAvailable return more information (api-breaking change)

- .github/workflows/label.yml
To only trigger on this specific repo
fixes #196
> conditional on label action

- res/android/values-es/aio_fpauth-strings.xml
Spanish translation had some spelling and syntax errors
> Fix spanish strings

- src/android/Fingerprint.java
Fix of the cancellation related bug.
> Null pointer exception fix

- src/android/BiometricActivity.java
- src/android/Fingerprint.java
- src/android/build.gradle
Switch this plugin to androidX and use biometric from  androidx.biometric.BiometricManager
> Switch to android x

- tests/tests.js
- www/Fingerprint.js
> Dmitry salnikov/master

- README.md
ngCordova is dead for a long time.
> Remove old examples

- README.md
- package.json
- plugin.xml
> Drop swift support plugin

- src/android/Fingerprint.java
Commented Fingerprint.java line 172 because is logging the biometric secret on load.
> Logging bug Fingerprint.java

- src/ios/Fingerprint.swift
> Fix xcode warn

- src/android/BiometricActivity.java
> Don't return plugin error if authentication failed

- src/ios/Fingerprint.swift
> Fix var from #376

- src/android/Fingerprint.java
- src/android/build.gradle
Closes #473
See: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:biometric/biometric/src/main/java/androidx/biometric/BiometricManager.java;drc=b8542ad2333442cb14bbc145a33920fb07fde745;l=701
> fix: replace can authenticate with compatible function
